### ISSUE TITLE
这个项目不太好使，https://github.com/xuhuigithub/spider1

### ISSUE THREAD

**Issue by xuhuigithub** [zzq798828932/autoOrderCarTraining#1]
不如试试这个：[https://github.com/xuhuigithub/spider1](https://github.com/xuhuigithub/spider1)

**Comment by xuhuigithub** [comment]
也非常感谢这个项目给的启发，只不过不会java没法提commit。打扰了

**Comment by neilismq** [comment]
哈哈，这个是自己学车时用的一个脚本，好久没更新了，没想到还能给人一点帮助，已经很满足了！

**Comment by neilismq** [comment]
> 也非常感谢这个项目给的启发，只不过不会java没法提commit。打扰了

哈哈，这个是自己学车时用的一个脚本，好久没更新了，没想到还能给人一点帮助，已经很满足了！

**Comment by xuhuigithub** [comment]
老哥，心态好抱拳了。🤩🤩
